// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
	// hashed password
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	LastLogin time.Time `json:"last_login"`
}

type Authtoken struct {
	ID        int64     `json:"id"`
	Token     string    `json:"token"`
	Account   int64     `json:"account"`
	CreatedAt time.Time `json:"created_at"`
	LastUsed  time.Time `json:"last_used"`
}

type Link struct {
	ID        int64     `json:"id"`
	Node      int64     `json:"node"`
	Link      string    `json:"link"`
	Clicks    int32     `json:"clicks"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

type Node struct {
	ID int64 `json:"id"`
	// parent_id is null for root node
	ParentID sql.NullInt64 `json:"parent_id"`
	Name     string        `json:"name"`
	IsDir    bool          `json:"is_dir"`
	Filesize sql.NullInt64 `json:"filesize"`
	// depth starting from parent node (0)
	Depth sql.NullInt32 `json:"depth"`
	// used for breadcrumbs
	Lineage   sql.NullString `json:"lineage"`
	Owner     sql.NullInt64  `json:"owner"`
	CreatedAt time.Time      `json:"created_at"`
}
